### ISSUE TITLE
Compile and release?

### ISSUE THREAD

**Issue by LeeBinder** [Frank-Siam/UEFI-BootLoader-winload.efi#1]
Hi @Frank-Siam - thanks for this project. I admit I don't know how to compile. I'd be interested in the 32bit winload32.efi. Would you be so kind and compile (best both archs for completion) and upload as release? That would be awesome.

**Comment by Frank-Siam** [comment]
This Project has not  a real use for others. It is only a empty placeholder for real stuff later. Sorry.

Gesendet von Mail für Windows 10

Von: LeeBinder
Gesendet: Samstag, 9. Mai 2020 08:37
An: Frank-Siam/UEFI-BootLoader-winload.efi
Cc: Subscribed
Betreff: [Frank-Siam/UEFI-BootLoader-winload.efi] Compile and release? (#1)

Hi Frank. Thanks for this project. I admit I don't know how to compile. I'd be interested in the 32bit winload32.efi. Would you be so kind and compile (best both archs for completion) and upload as release? That would be awesome.

**Comment by LeeBinder** [comment]
LOL OK. I'll keep on using legacy BIOS CSM + EFI w/ Clover 32 bit MBR then. Thanks for replying and take care.
